apiVersion: harness.io/v1
kind: Component
type: service
identifier: test05fentcv
name: test05-fentcv
owner: user:account/idp-release-automation-ui@harnessioprivate.testinator.com
spec:
  lifecycle: production
