apiVersion: harness.io/v1
kind: Component
type: service
identifier: test05mqefym
name: test05-mqefym
owner: user:account/idp-release-automation-ui@harnessioprivate.testinator.com
spec:
  lifecycle: production
