apiVersion: harness.io/v1
kind: Component
type: service
identifier: test05yeoppw
name: test05-yeoppw
owner: user:account/idp-release-automation-ui@harnessioprivate.testinator.com
spec:
  lifecycle: production
